### ISSUE TITLE
nfs_Create() doesn't try to handle v3 EXCLUSIVE semantics

### ISSUE THREAD

**Issue by dzafman** [phdeniel/nfs-ganesha#97]
Unlike the v4's open4_create() the v3's nfs_Create() function doesn't support the arg_create3.how.mode == EXCLUSIVE.  It should set the verifier in inode fields on create and if it finds them upon cache_inode_lookup() NOT return CACHE_INODE_ENTRY_EXISTS.

According to NFS v3 protocol spec we could return NFS3ERR_NOTSUPP, but that doesn't seem right since we are able to support this for v4 using FSAL.

**Comment by ffilz** [comment]
Exclusive create does work for NFS v4, I'm not quite sure what you're hitting.

It is a bit dodgy and will be improved in V2.4 with the multi-fd support.
